"""
Locust test targeting the public JSONPlaceholder API.

Endpoints used:
 - GET  /posts         (List)
 - GET  /posts/{id}    (Single)
 - POST /posts         (Create)
 - PUT  /posts/{id}    (Update)

Run:
    pip install locust
    locust -f locustfile_jsonplaceholder.py --host=https://jsonplaceholder.typicode.com

Headless example:
    locust -f locustfile_jsonplaceholder.py --headless -u 50 -r 5 --run-time 1m --host=https://jsonplaceholder.typicode.com
"""

import random
import uuid
from locust import HttpUser, task, between, SequentialTaskSet

LIST_ENDPOINT = "/posts"
SINGLE_ENDPOINT = "/posts/{id}"


def make_post_payload():
    uid = uuid.uuid4().hex[:6]
    return {
        "title": f"Test post {uid}",
        "body": "This is a test post generated by Locust",
        "userId": random.randint(1, 10),
    }


class PostFlow(SequentialTaskSet):
    def on_start(self):
        self.created_id = None

    @task(4)
    def get_list(self):
        self.client.get(LIST_ENDPOINT, name="GET List /posts")

    @task(3)
    def get_single(self):
        pid = random.randint(1, 100)
        self.client.get(SINGLE_ENDPOINT.format(id=pid), name="GET Single /posts/{id}")

    @task(2)
    def create_post(self):
        payload = make_post_payload()
        with self.client.post(LIST_ENDPOINT, json=payload, name="POST /posts", catch_response=True) as resp:
            if resp.status_code in (200, 201):
                try:
                    body = resp.json()
                    self.created_id = body.get("id")
                except Exception:
                    self.created_id = None
                resp.success()
            else:
                resp.failure(f"create failed: {resp.status_code}")

    @task(1)
    def update_post(self):
        if not self.created_id:
            return
        payload = make_post_payload()
        self.client.put(SINGLE_ENDPOINT.format(id=self.created_id), json=payload, name="PUT /posts/{id}")


class JSONPlaceholderUser(HttpUser):
    tasks = [PostFlow]
    wait_time = between(1, 3)


if __name__ == "__main__":
    print("Run with: locust -f locustfile_jsonplaceholder.py --host=https://jsonplaceholder.typicode.com")
