"""init

Revision ID: 2345fbd9f17d
Revises: 929f040d92a3
Create Date: 2026-08-18 13:49:02.952125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2345fbd9f17d'
down_revision: Union[str, None] = '929f040d92a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
