"""add user_accounts table

Revision ID: 929f040d92a3
Revises: 15f30cda159e
Create Date: 2026-08-18 13:47:46.488392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '929f040d92a3'
down_revision: Union[str, None] = '15f30cda159e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'bank_account_id', name='uq_user_bank_account')
    )
    op.create_index(op.f('ix_user_accounts_bank_account_id'), 'user_accounts', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_user_accounts_user_id'), 'user_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_accounts_user_id'), table_name='user_accounts')
    op.drop_index(op.f('ix_user_accounts_bank_account_id'), table_name='user_accounts')
    op.drop_table('user_accounts')
    # ### end Alembic commands ###
